
assignment1:
	gcc -o assignment1 assignment1.c

assignment2: assignment2.o
	gcc -o assignment2 assignment2.o

assignment2.o:
	as -o assignment2.o assignment2.s

clean:
	rm -f *.o assignment1 assignment2

